[package]
authors = ["Roma Sokolov", "Alexander Zhuravlev", "Jorge Aparicio <jorge@japaric.io>"]
name = "mpu9250"
version = "0.25.0"
description = "no_std driver for the MPU9250 & onboard AK8963 (accelerometer + gyroscope +  magnetometer IMU)"
keywords = ["arm", "cortex-m", "stm32", "hal"]
license = "MIT OR Apache-2.0"
readme = "README.md"
repository = "https://github.com/copterust/mpu9250"

[dependencies]
embedded-hal = "0.2.3"
bitflags = "1.0"
libm = { version = "0.2.1", optional = true }

[dev-dependencies]
linux-embedded-hal = "0.3"

[features]
# Enable the I2C MPU interface. This disables the SPI interface. All function
# names remain consistent. Arguments change from (SPI, nCS) pairs to (I2C, address) pairs
i2c = []
# Enable the use of the internal DMP features
dmp = ["libm"]
